/*
 * Automatically generated C config: don't edit
 */ 

/*
 * App
 */
#define CONFIG_ENABLE_APP_RS485D 1
#define CONFIG_ENABLE_APP_RS485C 1

/*
 * rs485c
 */
#undef CONFIG_RS485C_PROTOCOL_BACNET
#define CONFIG_RS485C_PROTOCOL_GENERAL 1
#undef CONFIG_RS485C_PROTOCOL_MODBUS

/*
 * Modules
 */
#undef CONFIG_ENABLE_MODULE_DAEMON
#define CONFIG_ENABLE_MODULE_MESSAGE_QUEUE 1
#undef CONFIG_ENABLE_MODULE_RINGBUFFER
#undef CONFIG_ENABLE_MODULE_WLIST
#undef CONFIG_ENABLE_MODULE_TIMER
#undef CONFIG_MODULE_TIMER_PERCISION_10MS
#undef CONFIG_MODULE_TIMER_PERCISION_50MS
#undef CONFIG_MODULE_TIMER_PERCISION_100MS
#undef CONFIG_MODULE_TIMER_PERCISION_500MS
#undef CONFIG_MODULE_TIMER_PERCISION_1S
#undef CONFIG_MODULE_TIMER_PERCISION_10S
#undef CONFIG_MODULE_TIMER_TICK_TYPE_SLEEP
#undef CONFIG_MODULE_TIMER_TICK_TYPE_SELECT
#undef CONFIG_ENABLE_MODULE_WBITMAP

/*
 * Framework
 */
#undef CONFIG_ENABLE_FRAME_BUS

/*
 * Miscellaneous
 */

/*
 * Development and Debugging
 */
#define CONFIG_ENABLE_ERROR_LOGS 1
#define CONFIG_ENABLE_WARNING_LOGS 1
#define CONFIG_DEBUG_BUILD 1
